# Generated by Django 6.0.8 on 2026-09-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitlab', '0002_corpus_v1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitlabinstance',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='historicalgitlabinstance',
            name='tags',
        ),
    ]
